### ISSUE TITLE
use TargetP v2 instad of v1

### ISSUE THREAD

**Issue by Rodolfo47** [elena-fc/Laccaria_MiSSPs_proyect#1]
Use the current version of the softhwere

**Comment by lyn320** [comment]
hi,
I ran the local version of targetp-2.0.Linux.tar.gz (Default parameters) and the slurm files report:
 # TargetP-2.0	Organism: Non-Plant	Timestamp: 20220309220806
# ID	Prediction	noTP	SP	mTP	CS Position
TRINITY_DN100003_c0_g1_i1.p3	noTP	0.958083	0.001913	0.040004	
TRINITY_DN100008_c0_g1_i1.p1	noTP	0.605158	0.013404	0.381438	
TRINITY_DN100089_c0_g1_i1.p1	noTP	0.999502	0.000194	0.000304
im confused about the 'noTP',can you tell me what does that mean and what can be my  Filter criteria(SP or SP plus noTP) if im looking for sequence targeting extracellular.
thank you so much!
